server:
  port: 8070

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db"
    username: "bestuser"
    password: "bestuser"
    driver-class-name: com.mysql.cj.jdbc.Driver

thymeleaf:
    prefix: classpath:/templates/